# Generated by Django 4.0.5 on 2022-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodapp', '0005_post_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
